# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: pmd

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '17 18 * * 4'

permissions:
  contents: read

jobs:
  pmd-code-scan:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
      - uses: pmd/pmd-github-action@v2
        with:
          rulesets: 'rulesets/java/quickstart.xml,ruleset.xml'
          analyzeModifiedFilesOnly: false
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: pmd-report.sarif

  build-v4-reviewbot-ongithub:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      # To report GitHub Actions status checks
      statuses: write
    steps:
      - name: codecheckout
        uses: actions/checkout@v4
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0


      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: uname
        run: uname -a

      - name: reviewbot
        uses: never/reviewbot@4d81aa21000609e4351eb742ce10ddc83f5db5be # x-release-please-version
        env:
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.TEST_GITHUB_TOKEN }}
  build-v4-linter-ongithub:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      # To report GitHub Actions status checks
      statuses: write
    steps:
      - name: codecheckout
        uses: actions/checkout@v4
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0


      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: uname
        run: uname -a

      - name: Super-linter
        uses: super-linter/super-linter/slim@v7.2.0 # x-release-please-version
        env:
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.TEST_GITHUB_TOKEN }}
  build-v5-test-infreshare:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      # To report GitHub Actions status checks
      statuses: write

      steps:
        - name: Run Infer#
          uses: microsoft/infersharpaction@v1.5
          id: runinfersharp
          with:
            binary-path: '<path to the binary directory containing .dlls and .pdbs>'

        - name: Upload SARIF output to GitHub Security Center
          uses: github/codeql-action/upload-sarif@v2
          with:
            sarif_file: infer-out/report.sarif

   
