# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: pmd

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '17 18 * * 4'

permissions:
  contents: read

jobs:
  pmd-code-scan:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    runs-on: ubuntu-latest
    steps:
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-java@v4
          with:
            distribution: 'temurin'
            java-version: '11'
        - uses: pmd/pmd-github-action@v2
          with:
            rulesets: 'ruleset.xml'
            analyzeModifiedFilesOnly: false
        - name: Upload SARIF file
          uses: github/codeql-action/upload-sarif@v3
          with:
            sarif_file: pmd-report.sarif
   
